apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: currency-exchange
  ports:
    - port: 8000
      targetPort: 8000
